log_level: TRACE  # TRACE WARNING

task:
    dataset: monado_slam
    # MOO07_mapping_easy  MOO11_short_3_backandforth
    video: MOO07_mapping_easy
    cam: cam0

    single_video_mode: True
    eda_mode: True  # True False

experiment:
    model: resnet
    loss: mse_loss
    name: ${experiment.model}_${experiment.loss}
    url: http://localhost:8080  # http://localhost:8080 file:///D:/thesis_code/keypoint_matcher/output

paths:
    roots:
        ws: D:/thesis_code # /home/stud/ath/ath_ws  D:/thesis_code
        mav: ${paths.roots.ws}/datasets/${task.dataset}/${task.video}/mav0
        project: ${paths.roots.ws}/keypoint_matcher
        output: ${paths.roots.project}/output

    output:
        logs: ${paths.roots.output}/${experiment.name}/logs
        checkpoints: ${paths.roots.output}/${experiment.name}/checkpoints
        val_images: ${paths.roots.output}/${experiment.name}/images/val
        test_images: ${paths.roots.output}/${experiment.name}/images/test

    matches: ${paths.roots.ws}/keypoint_dataset_pipeline/output/train/train_data.hdf5
    images: ${paths.roots.mav}/${task.cam}/data

image:
    # [width, height]
    original_image_shape: [640, 480]  # [640, 480]
    patch_size: 32
    patch_border: 4 # pixels

train:
    train_batch_size: 4
    val_batch_size: 4
    num_patches_per_image: 20

    fast_dev_run: False  # True False
    overfit_batches: 0

    patience: 5
    max_epochs: 5
    check_val_every_n_epoch: 1
    num_sanity_val_steps: 1
    log_every_n_steps: 1
    accumulate_grad_batches: 1
    learning_rate: 1e-4

val:
    num_patch_pairs_to_save: 24

test:
    batch_size: 4

loggers:
    - tensorboard
    - neptune

