log_level: TRACE  # TRACE WARNING

experiment:

    # model: shogun
    # linux: 53 

    # model: jason
    # linux: 75
    
    model: micky 
    linux: 57 

    # model: mando
    # linux: 60 
    
    params: 14mil
    heads: 1
    datasets: mix
    stddev: 4
    name: ${experiment.model}_${experiment.linux}_linux

    eda_mode: True  # True False

paths:
    roots:
#        ws: D:/thesis_code
        ws: /home/stud/ath/ath_ws
        mav: ${paths.roots.ws}/datasets/${task.dataset}/${task.video}/mav0
        project: ${paths.roots.ws}/keypoint_matcher
        output: ${paths.roots.project}/output/${experiment.name}

    output:
        logs: ${paths.roots.output}/logs
        checkpoints: ${paths.roots.output}/checkpoints
        train_images: ${paths.roots.output}/images/train
        val_images: ${paths.roots.output}/images/val
        test_images: ${paths.roots.output}/images/test

    images: ${paths.roots.mav}/${task.cam}/data


image:
    # [width, height]
    original_image_shape: [640, 480]  # [640, 480]
    crop_image_shape: [ 630, 476 ] # [504, 504] [630, 476]
    patch_size: 32  # 32  82  128
    patch_padding: 15
    

train:
    batch_size: 12 # 20  12
    accumulate_grad_batches: 4
    learning_rate: 1e-4   # 1e-4    

    fast_dev_run: True  # True False
    overfit_batches: 0

    patience: 10
    max_epochs: 10
    check_val_every_n_epoch: 2
    num_sanity_val_steps: 1
    log_every_n_steps: 10 # 100
    
val:
    num_patch_pairs_to_save: 80

test:
    batch_size: 4

loggers:
    #  - tensorboard
   - neptune
